/** process.envから読み取った環境変数。 */
export const {
  DISCORD_TOKEN,
  DISCORD_GUILD_ID,
  NOTIFY_TEXT_CHANNEL_ID,
  POMODORO_VOICE_CHANNEL_ID,
  DETECT_STICKER_RATE,
  AI_PROVIDER,
  AI_MODEL,
  AI_PROMPT_APPEND,
  AI_API_KEY,
  AI_CLOUDFLARE_ACCOUNT_ID
} = process.env;
